services:
  gateway:
    build: 
      context: ./backend/gateway
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT_GATEWAY: ${PORT_GATEWAY}
      POSTGRES_URL: ${POSTGRES_URL}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./backend/gateway:/usr/src/app

  data-science:
    build:
      context: ./data-science
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      DJANGO_ENV: ${DJANGO_ENV}
      DB_URL: ${DB_URL}
      SECRET_KEY: ${SECRET_KEY}
      BACKEND_URL: http://gateway:3001
      DJANGO_IGNORE_BACKEND_ERRORS: "True"
    volumes:
      - ./data-science:/usr/src/app

