services:
  gateway:
    build: 
      context: ./backend/gateway
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT_GATEWAY: ${PORT_GATEWAY}
      POSTGRES_URL: ${POSTGRES_URL}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./backend/gateway:/usr/src/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge