on:
  push:
    branches:
      - "main"
      - "develop"

jobs:
  CI-Backend-Deploy-Render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: List files in the repository
        run: ls -alh

      - name: Install dependencies
        run: |
          cd backend/gateway
          npm install

      - name: Build backend
        run: |
          cd backend/gateway
          npm run build

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL_BACKEND }}
        run: |
          curl "$deploy_url"