on:
  push:
    branches:
      - "**"  # Ejecutar en todas las ramas

jobs:
  CI-Build-And-Test:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Construir y verificar Frontend (Next.js)
      - name: Install and Build Frontend (Next.js)
        run: |
          echo "Building Next.js frontend..."
          cd front
          npm install
          npm run build

      # Paso 3: Construir y verificar Backend (NestJS)
      - name: Install and Build Backend (NestJS)
        run: |
          echo "Building NestJS backend..."
          cd backend/gateway
          npm install
          npm run build

      # Paso 4: Configurar y probar FastAPI
      - name: Test FastAPI (data)
        run: |
          echo "Setting up and testing FastAPI..."
          cd data
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python -m unittest discover
