on:
  push:
    branches:
      - "develop"

jobs:
  CI-Django-Deploy-Render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3"

      - name: Install dependencies
        working-directory: ./data-science
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL_DATA_SCIENCE }}
        run: |
          curl "$deploy_url"
