
on:
  push:
    branches:
      - "develop"

jobs:
  CI-FrontEnd-Deploy-Render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: List files in the repository
        run: ls -alh

      - name: Install dependencies for frontend
        run: |
          cd frontend/
          npm install

      - name: Build frontend
        run: |
          cd front/
          npm run build

      - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL_FRONT }}
        run: |
          curl -X POST "$deploy_url"
